name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: >
          Hi @${{ github.actor }}!! 👋
          Thank you for opening your first issue in this repository. We really appreciate your input! Our team will review your issue and get back to you as soon as possible.
          If you have any additional information or updates, feel free to add them here.
          Welcome to our community!
        pr-message: >
          Hello @${{ github.actor }}! 🎉
          Thank you for submitting your first pull request to this repository. Your contribution is greatly appreciated! Our team will review your pull request shortly.
          Please make sure that your PR follows our contribution guidelines. If you need any assistance or have any questions, don’t hesitate to ask.
          We’re excited to have you as a contributor. Welcome aboard!